import { CompanyAccount } from './class/CompanyAccount.js'
import { PeopleAccount } from './class/PeopleAccount.js'
import { TreineeAccount } from './class/TreineeAccount.js'

console.log('Criei conta pessoal do Wellington')
const peopleAccount: PeopleAccount = new PeopleAccount(1, 'Wellington', 10)
console.log('Depositei 100')
peopleAccount.deposit(100)
console.log('Saquei 50')
peopleAccount.withdraw(50)
console.log('O saldo agora é:')
console.log(peopleAccount.getBalance())
console.log('Informacoes gerais da conta:')
console.log('------------------------------------\n')
console.log(peopleAccount.getName() + '\n')
console.log(peopleAccount)
console.log('------------------------------------\n')

console.log('Criei conta comercial da Empresa')
const companyAccount: CompanyAccount = new CompanyAccount('Empresa', 20)
console.log('Depositei 200')
companyAccount.deposit(200)
console.log('Depositei 250')
companyAccount.deposit(250)
console.log('Saquei 400')
companyAccount.withdraw(400)
console.log('Emprestei 150')
companyAccount.getLoan(150)
console.log('O saldo agora é:')
console.log(companyAccount.getBalance())
console.log('Informacoes gerais da conta:')
console.log('------------------------------------\n')
console.log(companyAccount.getName() + '\n')
console.log(companyAccount)
console.log('------------------------------------\n')

console.log('Criei conta do Estagiario Joao')
const treineeAccount: TreineeAccount = new TreineeAccount('Joao',3434)
console.log('Depositei 100')
treineeAccount.deposit(100)
console.log('O saldo agora é:')
console.log(treineeAccount.getBalance())
console.log('Informacoes gerais da conta:')
console.log('------------------------------------\n')
console.log(treineeAccount)
console.log('------------------------------------\n')
